spring:
   datasource:
       url: jdbc:mysql://127.0.0.1/study?useUnicode=true&characterEncoding=utf-8
       username: root
       password: 123456
       driver-class-name: com.mysql.jdbc.Driver

   jpa:
       database: mysql
       show-sql: true
       hibernate:
            ddl-auto: update
       properties:
           dialect: org.hibernate.dialect.MySQL5Dialect

   thymeleaf:
       cache: false
       mode: LEGACYHTML5